[GModelFitViewer_artifact]
git-tree-sha1 = "664814daa55acd78b051d9a93fba2cf4fa689648"

    [[GModelFitViewer_artifact.download]]
    sha256 = "1ce545cfd57a8f4019daa86ed3b6635e4274b2cdd1f9239ff3bd12bd19b626e3"
    url = "https://qsfit.inaf.it/GModelFitViewer/GModelFitViewer_artifact.tar.gz"
