[GFitViewer_artifact]
git-tree-sha1 = "cccad926589a0d8511575b7ea69a083ba23ca016"

    [[GFitViewer_artifact.download]]
    sha256 = "56add5dedd0e529dae06751bbff6ad47734f8a50c048837f15f63c992986caf5"
    url = "https://qsfit.inaf.it/GFitViewer/GFitViewer_artifact.tar.gz"
