[GModelFitViewer_artifact]
git-tree-sha1 = "533fe8c24585f57cb15b5d2eb8632366c492f732"

    [[GModelFitViewer_artifact.download]]
    sha256 = "9403a1422a5acd8ad4ddb3d94dbe9a6f3037450cc97a8ecc9da12be2a0188085"
    url = "https://qsfit.inaf.it/GModelFitViewer/GModelFitViewer_artifact.tar.gz"
