[GFitViewer_artifact]
git-tree-sha1 = "70f156ad2fff673f74ab8ff85cb2e7ffa7e3f5ce"

    [[GFitViewer_artifact.download]]
    sha256 = "41ab8c9e45d6d23e49f90aad7ac3c29010180f33032a7794db7f9f3231685866"
    url = "https://qsfit.inaf.it/GFitViewer/GFitViewer_artifact.tar.gz"
