[GFitViewer_artifact]
git-tree-sha1 = "9c3fe85e47fb69ac95b15ada81e9694597f7864e"

    [[GFitViewer_artifact.download]]
    sha256 = "395ea8f9ebdac0627dcbdbeda4ba77e4a56bf16e491cce9ee56f87b263285ace"
    url = "https://qsfit.inaf.it/GFitViewer/GFitViewer_artifact.tar.gz"
