[GFitViewer_artifact]
git-tree-sha1 = "fae317a2e6922b3e0419ea47653e147a9d99b9e5"

    [[GFitViewer_artifact.download]]
    sha256 = "3db88ddb50b7f7dd8c8b299f8aade2ab20090a4bc38ae1b56de9267d21362866"
    url = "https://qsfit.inaf.it/GFitViewer/GFitViewer_artifact.tar.gz"
